# Generated by Django 6.0.4 on 2026-04-22 23:28

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=django_quill.fields.QuillField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
