# Generated by Django 6.0.4 on 2026-04-18 14:46

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_alter_note_options_note_content_json_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='content_json',
        ),
        migrations.AddField(
            model_name='note',
            name='content_rich',
            field=django_quill.fields.QuillField(blank=True, null=True, verbose_name='Contenu enrichi'),
        ),
    ]
