# Generated by Django 6.0.4 on 2026-04-20 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0003_remove_note_content_json_note_content_rich'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='content',
        ),
    ]
