# Generated by Django 6.0.4 on 2026-04-21 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0005_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='ip_adress',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP'),
        ),
    ]
