# Generated by Django 6.0.4 on 2026-04-22 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0006_log_ip_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='action',
            field=models.CharField(choices=[('login', 'Connexion'), ('login_failed', 'Tentative de connexion échouée'), ('logout', 'Déconnexion'), ('note_create', 'Création de note'), ('note_update', 'Modification de note'), ('note_delete', 'Suppression de note'), ('system', 'Evénement système')], max_length=50, verbose_name='Action'),
        ),
    ]
