# Generated by Django 6.0.4 on 2026-04-24 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0007_alter_log_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='action',
            field=models.CharField(choices=[('login', 'Connexion'), ('login_failed', 'Tentative de connexion échouée'), ('logout', 'Déconnexion'), ('note_create', 'Création de note'), ('note_update', 'Modification de note'), ('note_delete', 'Suppression de note'), ('task_create', 'Création de tâche'), ('task_update', 'Modification de tâche'), ('task_delete', 'Suppression de tâche'), ('system', 'Evénement système')], max_length=50, verbose_name='Action'),
        ),
    ]
